### ISSUE TITLE
Error when running `../configure`

### ISSUE THREAD

**Issue by MayaGans** [lionel-/contributing#7]
Hiya! Firstly thanks for this awesome resource, I'm VERY green so I'm sorry if this is absolute noob but I'm working through this and ran `../configure` inside the `build` folder we created but I got the error: 

```
No Fortran compiler found
```

What's the recommended way of installing this? 

[Somewhat related I don't know how much prior knowledge is assumed for the bookdown but it took me a minute to chase down that I needed to run `brew install wget` to get the tweaking files 😊 ]

Thanks again!!

**Comment by MayaGans** [comment]
Update: I used `brew install gcc` and got a little further....
I got the error `PCRE2 library and headers are required, or use --with-pcre1 and PCRE >= 8.32 with UTF-8 support`
So then I ran `../configure --with-pcre1` **[I'm wondering why you _didn't_ have to do that? ]**


And THEN I got the error: `libcurl >= 7.28.0 library and headers are required with support for https` 🤦‍♀️ 
I found [some stackoverflow post](https://stackoverflow.com/questions/46013341/error-libcurl-7-22-0-library-and-headers-are-required-with-support-for-https) that say to `sudo apt-get install libcurl4-openssl-dev` but I'm not sure that's the solution for MacOS? This one doesn't seem to be as easy as `gcc`

Sorry if this is all super basic and I have no idea how specific this problem is to me.... 

Maybe it'd beyond the scope of the bookdown but I think it'd be nice to have a little section on what is needed on your machine prior to running `../configure` and some instructions on how to obtain those libraries? 🤷

**Comment by MayaGans** [comment]
Alright one more step further after removing Anaconda from my path! 

But now I got the message:

```
configure: error: Some of the recommended packages are missing
  Use --without-recommended-packages if this was intentional
```

So I'm not sure if I should add `--without-recommended-packages` or if I needed to download packages like `MASS` in order to continue with the book?

**Comment by MichaelChirico** [comment]
Hey @MayaGans, finally have a computer so can help a bit. I also just installed R from source on my Ubuntu laptop & ran into some of these same issues... it might help to have a look at this section of the "R Administration" manual:

https://cran.r-project.org/doc/manuals/R-admin.html#Essential-and-useful-other-programs-under-a-Unix_002dalike

This will at least tell you what all programs are needed on your machine to get R installed from source, and a little idea of why. What's missing is a "how" which presumably they've left out because the answer is "it depends" :slightly_frowning_face:

**Comment by lionel-** [comment]
Thanks for the suggestions. I just added some `brew` invokations and a link for installing gfortran to the troubleshooting section.
